name: sample

configs:
  Debug LOCAL: debug
  Debug INET: debug
  Production: release 

options:
  bundleIdPrefix: ru.sample
  developmentLanguage: en
  deploymentTarget:
    iOS: 15.0
    defaultConfig: Debug
  preGenCommand: swiftgen
  groupSortPosition: bottom
  groupOrdering:
    - order: [App, Core, Networking, UI]
packages:
  Reusable:
    url: https://github.com/AliSoftware/Reusable.git
    from: 4.1.0
  Dip:
    url: https://github.com/AliSoftware/Dip
    from: 7.1.1
  DifferenceKit:
    url: https://github.com/ra1028/DifferenceKit.git
    from: 1.3.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.0.1
  netfox:
    url: https://github.com/kasketis/netfox.git
    from: 1.21.0    
  Loady:
    url: https://github.com/farshadjahanmanesh/loady.git
    from: 1.0.8
  SwiftMessages:
    url: https://github.com/SwiftKickMobile/SwiftMessages
    from: 10.0.0   
  ProgressHUD:
    url: https://github.com/relatedcode/ProgressHUD.git
    from: 14.1.3
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.9.1
  AlamofireImage:
    url: https://github.com/Alamofire/AlamofireImage.git
    from: 4.3.0   
  PersistenceKit:
    url: https://github.com/Teknasyon-Teknoloji/PersistenceKit.git
    from: 1.4.0  
  CocoaLumberjack: 
    url: https://github.com/CocoaLumberjack/CocoaLumberjack.git
    from: 3.8.0
  netfox: 
    url: https://github.com/kasketis/netfox
    from: 1.21.0
  SwiftRichString:
    url: https://github.com/malcommac/SwiftRichString.git
    from: 3.5.0 
  SkeletonView:
    url: https://github.com/Juanpe/SkeletonView.git
    from: 1.7.0 
targets:
  sample:
    templates:
      - Application
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ru.sample.ios
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-sample
        APPLICATION_TYPE: "sample"
        BUNDLE_DISPLAY_NAME: "sample"
        CODE_SIGN_ENTITLEMENTS: "App/Supporting Files/sample.entitlements"
      configs:
        Debug LOCAL:
          CURRENT_SCHEME_NAME: "Debug-Local"
          PRODUCT_NAME: sampledev
          PROVISIONING_PROFILE_SPECIFIER: Wildcard
        Debug INET:
          CURRENT_SCHEME_NAME: "Debug-Inet"
          PRODUCT_NAME: sampledev
          PROVISIONING_PROFILE_SPECIFIER: Wildcard  
        Production:
          CURRENT_SCHEME_NAME: "Production"
          PRODUCT_NAME: sampleproduction
          PROVISIONING_PROFILE_SPECIFIER: Wildcard
  Core:
    templates: 
      - Framework
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: "$(SRCROOT)/Core/Supporting Files/Bridging-Header.h"
        SWIFT_OBJC_INTERFACE_HEADER_NAME: "Core-Swift.h"    
    sources: [Core]
    dependencies:
      - package: CocoaLumberjack
        product: CocoaLumberjackSwift
      - package: CocoaLumberjack
        product: CocoaLumberjack   
  UI:
    templates: 
      - Framework
    sources: [UI]
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: "$(SRCROOT)/UI/Supporting Files/Bridging-Header.h"
        SWIFT_OBJC_INTERFACE_HEADER_NAME: "UI-Swift.h"    
    info:
      path: UI/Supporting Files/Info.plist
      properties:
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1.0.0"
    preBuildScripts:
      - path: "UI/Supporting Files/Scripts/swiftgen.sh"
        name: Swiftgen
    dependencies:
      - target: Core
      - package: SwiftMessages
        product: SwiftMessages    
      - package: SkeletonView
        product: SkeletonView
      - package: DifferenceKit
        product: DifferenceKit
      - package: SnapKit
        product: SnapKit
      - package: Reusable
        product: Reusable

  Networking:
    templates: 
      - Framework
    sources: [Networking]
    settings:
      configs:
        Debug:
          BASE_URL: "http://192.168.88.254"
        Production:
          BASE_URL: "http://192.168.88.254"
    preBuildScripts:
      - path: "Networking/Supporting Files/Scripts/swiftgen.sh"
        name: Swiftgen
    dependencies:
      - target: Core
      - package: Alamofire
        product: Alamofire
      - package: AlamofireImage
        product: AlamofireImage
      - package: Dip
        product: Dip


settings:
  base:
    SUPPORTS_MACCATALYST: NO
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
    SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: YES
  configs:
    Debug LOCAL:
      SWIFT_COMPILATION_MODE: singlefile
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      VALIDATE_PRODUCT: NO
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"      
    Debug INET:
      SWIFT_COMPILATION_MODE: singlefile
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      VALIDATE_PRODUCT: NO
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
    Production:
      ENABLE_TESTABILITY: NO
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
      VALIDATE_PRODUCT: YES

targetTemplates:
  Framework:
    type: framework
    supportedDestinations: [iOS]
    deploymentTarget: 15.0      
    settings:
      base:
        MARKETING_VERSION: 1.0
        SWIFT_VERSION: 5.0
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: YES
  Application:
    # scheme:
    #   configVariants:
    #     - DEV
    #     - Production
    type: application
    supportedDestinations: [iOS]
    sources:
      - path: App
      - path: UI/Resources/Assets.xcassets
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        ENABLE_BITCODE: false
        DEVELOPMENT_TEAM: Z111111111
        LAUNCH_SCREEN: "Launch Screen"
        SWIFT_OBJC_BRIDGING_HEADER: "$(SRCROOT)/App/Supporting Files/Bridging-Header.h"
        INFOPLIST_FILE: "App/Resources/Info.plist"
        OTHER_SWIFT_FLAGS: "$(inherited) -Xfrontend -debug-time-function-bodies"
        SWIFT_OBJC_INTERFACE_HEADER_NAME: "sample-Swift.h"
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: YES
      configs:
        Debug LOCAL:
          ENVIRONMENT: "Debug"
          NETFOX: "YES"
          CODE_SIGN_IDENTITY: "iPhone Developer"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Debug INET:
          ENVIRONMENT: "Debug"
          NETFOX: "YES"
          CODE_SIGN_IDENTITY: "iPhone Developer"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Production:
          ENVIRONMENT: "Production"
          NETFOX: "NO"
          CODE_SIGN_IDENTITY: "iPhone Distribution"
    preBuildScripts:
      - path: "App/Supporting Files/Scripts/swiftgen.sh"
        name: Swiftgen
    dependencies:
      - target: Core
      - target: UI
      - target: Networking
      - package: Reusable
        product: Reusable    
      - package: Dip
        product: Dip
      - package: DifferenceKit
        product: DifferenceKit
      - package: SnapKit
        product: SnapKit
      - package: Loady
        product: Loady
      - package: SwiftMessages
        product: SwiftMessages
      - package: CocoaLumberjack
        product: CocoaLumberjackSwift
      - package: CocoaLumberjack
        product: CocoaLumberjack
      - package: netfox
        product: netfox
      - package: SwiftRichString
        product: SwiftRichString  
